#!/bin/bash

DB_NAME="demo_small"                                         # Имя базы данных, которую мы будем загружать
DB_URL="https://edu.postgrespro.ru/demo-small-20161013.zip"  # URL для скачивания архивированного файла базы данных

wget $DB_URL -O /tmp/database.zip                            # Загружаем файл по указанному URL и сохраняем его как /tmp/database.zip

 gunzip /tmp/database.zip -d /tmp/database                   # Распаковываем загруженный zip-файл в директорию /tmp/database

 SQL_FILE=$(find /tmp/database -name "*.sql" -print -quit)   # Находим первый файл с расширением .sql в распакованной директории и сохраняем его путь в переменную SQL_FILE

 if [ -f "$SQL_FILE" ]; then                                 # Проверяем, существует ли файл SQL_FILE

    psql -U useradm -d postgres -f "$SQL_FILE"               # Если файл существует, импортируем его в базу данных postgres с использованием пользователя useradm
    echo "База данных загружена и импортирована из $SQL_FILE."
 else
    echo "SQL файл не найден в распакованном архиве."
 fi



